## 1.创建
### 1.1 数值类型
- 标量，维度为0，如1，2，3.4
- 向量，维度为1，如[1，2]，[3.2，5.4]，长度为n
- 矩阵，维度为2，如[[1,2],[3,4]]，形状为n*m
- 张量（tensor），所有维度数>2的数组统称为张量
- 在tensorflow中，我们将标量，向量，矩阵都称为张量

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 创建标量, dtype为保存精度，有int16, int32, float16, float32, float64等
a = tf.constant(1, dtype = tf.int16)
# 创建一个向量
b = tf.constant([1,2,3])
# 创建一个矩阵
c = tf.constant([[1,2],[3,4]], dtype = tf.float32)
# 创建一个张量
d = tf.constant([[[1,2],[3,4]],[[5,6], [7,8]]])

In [3]:
# 判断是否是张量
type(a), tf.is_tensor(a), tf.is_tensor(b), tf.is_tensor(c), tf.is_tensor(d)

(tensorflow.python.framework.ops.EagerTensor, True, True, True, True)

In [4]:
# 变量信息
a, b, c, d

(<tf.Tensor: id=0, shape=(), dtype=int16, numpy=1>,
 <tf.Tensor: id=1, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: id=3, shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>)

id是tensorflow中内部索引对象的编号，shape是张量的形状，dtype表示张量的数值精度，张量numpy()方法可以返回numpy.array

In [5]:
np.array(a), np.array(b), np.array(c), np.array(d)

(array(1, dtype=int16),
 array([1, 2, 3]),
 array([[1., 2.],
        [3., 4.]], dtype=float32),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]))

In [6]:
a.numpy(), b.numpy(), c.numpy(), d.numpy()

(1,
 array([1, 2, 3]),
 array([[1., 2.],
        [3., 4.]], dtype=float32),
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]))

In [7]:
# 通过dtype查看保存属性
a.dtype, c.dtype

(tf.int16, tf.float32)

In [8]:
# 通过tf.cast转换保存精度
c = tf.cast(c, tf.float64)
c.dtype

tf.float64

### 1.2 字符串类型
tf.strings提供了很多字符串类型的工具

In [9]:
e = tf.constant('Hello World')
e

<tf.Tensor: id=5, shape=(), dtype=string, numpy=b'Hello World'>

In [10]:
tf.strings.lower(e)

<tf.Tensor: id=6, shape=(), dtype=string, numpy=b'hello world'>

### 1.3 布尔类型

In [11]:
f = tf.constant(True)
g = tf.constant([True, False])

In [12]:
f, g

(<tf.Tensor: id=7, shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: id=8, shape=(2,), dtype=bool, numpy=array([ True, False])>)

In [13]:
# 布尔类型也可以与整形转换，在tensorflow中，不是0的数字都是True
h = tf.cast(f, tf.int16)
i = tf.cast(c, tf.bool)
h,i

(<tf.Tensor: id=9, shape=(), dtype=int16, numpy=1>,
 <tf.Tensor: id=10, shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

### 1.4 待优化张量
使用tf.Variable或者GradientTape.watch()方法将张量设置为待优化的张量，这样就可以自动计算梯度信息

In [14]:
# 使用tf.Variable将一个张量加入待更新列表中
cc = tf.Variable(c)
cc.name, cc.trainable

('Variable:0', True)

In [15]:
# 使用GradientTape.watch()方法
# 创建张量
a = tf.constant(1.)
b = tf.constant(2.)
c = tf.constant(3.)
w = tf.constant(4.)

# 构建梯度环境
with tf.GradientTape() as tape:
    # 将w和a加入梯度跟踪列表，这样之后计算梯度时可以计算w和a，但是无法计算b和c
    tape.watch([w, a]) 
    y = a * w ** 2 + b * w + c # 公式

# 对w和a分别进行求导，但是GradientTape.gradient只能call一次
[dy_dw, dy_da] = tape.gradient(y, [w, a])
print(dy_dw, dy_da)

tf.Tensor(10.0, shape=(), dtype=float32) tf.Tensor(16.0, shape=(), dtype=float32)


### 1.5 将numpy adarray和python list转换成tensor

In [16]:
a = tf.convert_to_tensor([1,2,3])
b = tf.constant([1,2,3])
a,b

(<tf.Tensor: id=39, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: id=40, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

可以发现两个方法的结果是一样的，我们使用其中一个就可以了

### 1.6 创建全0，全1张量

In [17]:
# 创建全0
a = tf.zeros([1,2,3])

# 创建全1
b = tf.ones([1,2,3])
a, b

(<tf.Tensor: id=43, shape=(1, 2, 3), dtype=float32, numpy=
 array([[[0., 0., 0.],
         [0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: id=46, shape=(1, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>)

In [18]:
# 创建一个与一个矩阵形状相同的全0和全1
c = tf.zeros_like(b)
d = tf.ones_like(a)
c, d

(<tf.Tensor: id=47, shape=(1, 2, 3), dtype=float32, numpy=
 array([[[0., 0., 0.],
         [0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: id=50, shape=(1, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>)

In [19]:
# 也可以通过.shape来实现
e = tf.zeros(c.shape)
e

<tf.Tensor: id=53, shape=(1, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

### 1.7 创建自定义数值的张量

In [20]:
a = tf.fill([1,2,3], 100)
a

<tf.Tensor: id=56, shape=(1, 2, 3), dtype=int32, numpy=
array([[[100, 100, 100],
        [100, 100, 100]]])>

### 1.8 创建已知分布的张量

In [21]:
# 创建符合正态分布的张量（从正态分布中进行随机抽样形成的张量）
tf.random.normal([1,2,3], mean = 1, stddev = 4)

<tf.Tensor: id=62, shape=(1, 2, 3), dtype=float32, numpy=
array([[[ 0.3895052 ,  9.308348  ,  0.54359734],
        [-0.84032714,  2.4388733 ,  0.03512162]]], dtype=float32)>

这是从一个三维的正态分布中进行随机抽样形成的张量，它们的均值为1，标准差为4

In [22]:
# 创建均匀分布的张量
tf.random.uniform([1,2,3], maxval = 10, minval = 1)

<tf.Tensor: id=69, shape=(1, 2, 3), dtype=float32, numpy=
array([[[6.4818516, 8.837896 , 1.3831772],
        [4.213144 , 4.9849396, 9.014647 ]]], dtype=float32)>

也可以指定仅采样整形，这时加上dtype = tf.int32就行了

### 1.9 创建序列

In [23]:
tf.range(1, 10, delta = 2)

<tf.Tensor: id=73, shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

从1开始，步长为2，最大为10的序列

## 2.数值的用途
### 2.1 标量
标量主要用于误差值和各种测量指标的表示，比如：
- 准确度
- 精度
- 召回率
- ……

### 2.2 向量

- 偏置向量b
- ……

### 2.3 矩阵
- 全连接层的批量输入
- ……

### 2.4 3维张量
- 序列信号
- ……

### 2.5 4维张量
- 特征图
- ……